chore: fix depr warning by updating import: xblockutils -> xblock.utils
open-craft/xblock-poll pull request #127
Opened 2024-01-09 14:51 UTC by kdmccormick

Context: https://github.com/openedx/XBlock/issues/675

Fixes some edx-platform warnings:
```
2024-01-09 14:45:42,875 WARNING 289 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/poll/poll.py:40: DeprecatedPackageWarning: Please use import xblock.utils.publish_event instead of xblockutils.publish_event because the 'xblock-utils' package has been deprecated and migrated to within 'xblock' package. 
  from xblockutils.publish_event import PublishEventMixin

2024-01-09 14:45:42,875 WARNING 289 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/poll/poll.py:41: DeprecatedPackageWarning: Please use import xblock.utils.resources instead of xblockutils.resources because the 'xblock-utils' package has been deprecated and migrated to within 'xblock' package. 
  from xblockutils.resources import ResourceLoader

2024-01-09 14:45:42,875 WARNING 289 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/poll/poll.py:42: DeprecatedPackageWarning: Please use import xblock.utils.settings instead of xblockutils.settings because the 'xblock-utils' package has been deprecated and migrated to within 'xblock' package. 
  from xblockutils.settings import ThemableXBlockMixin, XBlockWithSettingsMixin
```

Bumps version from 1.13.0 to 1.13.1

2024-01-09 15:08 UTC, Agrendalath requested changes
Thanks for preparing this, @kdmccormick!

One request - could we make this change backward-compatible, as, e.g., we did [here](https://github.com/openedx/xblock-drag-and-drop-v2/pull/357#discussion_r1365586601)?

2024-01-09 15:57 UTC, kdmccormick commented
Sure thing @Agrendalath . Ready for another look.

2024-01-09 16:20 UTC, kdmccormick commented
Good questions @Agrendalath . I wasn't aware that not all modules were copied from xblockutils to xblock.utils.

I see the [justification for removing base_test.py](https://github.com/openedx/xblock-drag-and-drop-v2/pull/357#issuecomment-1761573296) is that bok-choy is deprecated, but it seems like xblock-poll uses base_test.py for integration testing without actually relying on bok-choy at all. The integration tests seem to be working fine in this repository and I'd hate to remove them for no reason. I'm wondering now whether it was a mistake to drop base_test.py. What do you think?

2024-01-09 17:55 UTC, bradenmacdonald commented
It looks like [`base_test.py`](https://github.com/openedx-unsupported/xblock-utils/blob/7a88cb9b5cc56ff6b23f6ffcb320667b1ea27e92/xblockutils/base_test.py) is still useful yep, as it can be used for "plain" selenium integration tests, without any bok-choy. In fact there's no code related to bok-choy in that file that I can see.

My suggestion is that since `base_test.py` is so tightly coupled with `workbench`, we move it into the `xblock-sdk` repo and combine it with [`test_utils.py`](https://github.com/openedx/xblock-sdk/blob/master/workbench/test_utils.py) which seems to have related functionality.

2024-02-07 15:01 UTC, farhan commented
@kdmccormick its under discussion here
https://github.com/openedx/xblock-sdk/issues/345#issuecomment-1910343675

2024-02-07 15:11 UTC, kdmccormick commented
@bradenmacdonald and @Agrendalath : @farhan [dug in and found](https://github.com/openedx/xblock-sdk/issues/345#issuecomment-1910343675) that SeleniumXBlockTest was actually using bok-choy's WebAppTest as a base, so it seems that it was right to remove it instead of pulling it into XBlock.

Unless you have any objections, I'll remove this XBlock's selenium tests and update requirements/base.in to point at `XBlock[django]`.

2024-03-18 16:39 UTC, kdmccormick commented
This ended up being more work than I'm able to take on right now. I'm going to add some notes to https://github.com/open-craft/xblock-poll/issues/114 and close this. Feel free to re-use this PR in the future if that's helpful.

2024-03-18 16:39 UTC, closed without merging